export class Info {
    constructor(
        public stationnum: string,
        public observtimes: string,
        public winddirect: number,
        public windvelocity: number,
        public winddirect10: number,
        public windvelocity10: number,
        public maxwindd: number,
        public maxwindv: number,
        public timemaxwind: number,
        public instantwindd: number,
        public instantwindv: number,
        public exmaxwindd: number,
        public exmaxwindv: number,
        public timeexmaxwind: number,
        public precipitationamount: null,
        public precipitation: number,
        public drybultemp: number,
        public maxtemp: number,
        public timemaxtemp: number,
        public mintemp: number,
        public timemintemp: number,
        public relhumidity: number,
        public minrelhumidity: number,
        public timeminrelh: number,
        public vapourpress: number,
        public dewtemp: number,
        public stationpress: number,
        public maxpsta: number,
        public timemaxpsta: number,
        public minpsta: number,
        public timeminpsta: number,
        public sealevelpress: number,
        public sync_inserttime: string,
        public md5: string,
    ) { }
}
